### ISSUE TITLE
Error 500 when no address specified

### ISSUE THREAD

**Issue by arietrouw** [XYOracleNetwork/api-archivist-nodejs#99]
Call from Kotlin SDK causes this:

archivist  | Cannot read properties of undefined (reading 'length')
archivist  | TypeError: Cannot read properties of undefined (reading 'length')
archivist  |     at XyoBoundWitnessBodyValidator.addresses (/app/node_modules/src/core/BoundWitness/Validator/BodyValidator.ts:29:19)
archivist  |     at XyoBoundWitnessBodyValidator.all (/app/node_modules/src/core/BoundWitness/Validator/BodyValidator.ts:93:15)
archivist  |     at XyoBoundWitnessValidator.all (/app/node_modules/src/core/BoundWitness/Validator/Validator.ts:45:50)
archivist  |     at /src/archive/archive/block/post/validateBody.ts:9:32
archivist  |     at Array.map (<anonymous>)
archivist  |     at validateBody (/src/archive/archive/block/post/validateBody.ts:7:25)
archivist  |     at /src/archive/archive/block/post/post.ts:26:28
archivist  |     at Generator.next (<anonymous>)
archivist  |     at /app/node_modules/tslib/tslib.js:117:75
archivist  |     at new Promise (<anonymous>)

Probably an issue in the client

**Comment by JoelBCarter** [comment]
@arietrouw Do we want to change things on the Kotlin side or allow blocks with no addresses to be sent on the server side?

**Comment by arietrouw** [comment]
Turned off validation in post for now until we can get signatures to line up

**Comment by arietrouw** [comment]
Next step is returning validation errors in meta
